### ISSUE TITLE
Add application flow chart to wiki 

### ISSUE THREAD

**Issue by zacck-zz** [LittleKidogo/quick_bytes_backend#1]
Add an application flowchart for how the application works to the wiki

**Comment by zacck-zz** [comment]
@br4inii  @WanjikuMac  let's get this drawn up and added to the wiki of this project as soon as possible I can help with whatever is needed but out blog basically works the following way 

-  We have authors who can write, edit and delete posts and comments
- We have posts that have a number of posts 
- We have comments that belong to a post 

The application at its full capacity would 
- [x] enable authors to authenticate into the system #6 
- [x] enable authors to write, edit, save, publish and delete posts #7 
- [x] enable authors and readers to add comments to posts #8 
- [x] enable readers to search for manuals #9 


Please let me know if I need to explain this further

**Comment by zacck** [comment]
Hey @WanjikuMac  @br4inii  checkout the [wiki](https://github.com/LittleKidogo/quick_bytes_backend/wiki) for the designs of the app and the [flows](https://github.com/LittleKidogo/quick_bytes_backend/wiki/flows) for the application logic

**Comment by zacck** [comment]
@WanjikuMac  @br4inii  we can use this Epic for the hackathon deliverables this evening
