### ISSUE TITLE
Resolvers Epic

### ISSUE THREAD

**Issue by zacck-zz** [LittleKidogo/quick_bytes_backend#16]
## Expected Behavior
We need resolvers and schema that need to enable users to communicate and transact with the backend the following actions need to covered and each can be a separate issue or epic even !

- [x] enabler user to publish a manual if they are logged into the system with a role of publisher
- [x] enable a user to add a manual if they are logged into the system with a role of editor or publisher
- [x] enable a user to add a comment to a manual if they are logged into the system  
- [x] enable a user to login by providing a profile username and a user password 
- [x] enable a user to sign up by providing the details needed to create a user account 

## Actual Behavior

Not Implemented at the moment 

## Acceptance Criteria

We should cover all the above functionalities for the client 

## Steps to Reproduce the Problem
  1. There are no API endpoints to interact with the app

## Specifications

  - Version:

**Comment by zacck-zz** [comment]
@br4inii @WanjikuMac  Using the absinthe book we can break out and detail issues in this epic for the morning part of the prep

**Comment by zacck-zz** [comment]
# Notes 
1. Build a Schema for the app 
2. Setup middleware 
3. Start building queries and mutations and resolvers
